### ISSUE TITLE
libXrandr.so.2 problem after memento-bg

### ISSUE THREAD

**Issue by Aibfoba** [apirrone/Memento#76]
**6.5.0-15-generic**
**Linux machine 6.5.0-15-generic #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC x86_64 x86_64 x86_64 GNU/Linux**
**Linux Mint**
**i5 12400 integrated graphics**

useruser1@computerr:/$ memento-bg
pygame 2.5.0 (SDL 2.28.0, Python 3.10.8)
Hello from the pygame community. https://www.pygame.org/contribute.html
No OPENAI_API_KEY environment variable found, LLM related features will not be available
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/memento-bg", line 33, in <module>
    sys.exit(load_entry_point('memento', 'console_scripts', 'memento-bg')())
  File "/home/useruser1/Documents/folder1/folder2/memento/memento/__init__.py", line 6, in bg
    backgound = Background()
  File "/home/useruser1/Documents/folder1/folder2/memento/memento/background.py", line 62, in __init__
    self.sct = mss.mss()
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/site-packages/mss/factory.py", line 34, in mss
    return linux.MSS(**kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/site-packages/mss/linux.py", line 302, in __init__
    self.xrandr = cdll.LoadLibrary(_XRANDR)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libXrandr.so.2: cannot open shared object file: No such file or directory

**_Tried this, but issue remains:_**

 2054  sudo aptitude install libxrandr2
 2055  sudo aptitude install libxrandr2:i386
 2057  sudo aptitude install libxrandr-dev
 2058  sudo apt install libxrandr-dev:i386 

_Sorry, guys, if i am stupid. I am a newbie and i created this github account only to solve this issue and use your soft._
_Great software, btw._

**Comment by apirrone** [comment]
Hi! 

Looks like the an issue with the `mss` library that I use for capturing screenshots. It could be because your linux install does not use X at first glance, but I may be mistaken. 

Could you give me more details on your linux installation? It looks like you are using "linuxbrew" but I don't know what it is. Is this a native linux install ? or something like WSL or a MacOS equivalent ?

Thanks for the support !

**Comment by Aibfoba** [comment]
> Looks like the an issue with the `mss` library that I use for capturing screenshots. It could be because your linux install does not use X at first glance, but I may be mistaken.
>
> Could you give me more details on your linux installation? It looks like you are using "linuxbrew" but I don't know what it is. Is this a native linux install ? or something like WSL or a MacOS equivalent ?

Hello. Thank you for your reply.

This is typical Linux Mint installation, 

```
System:
  Kernel: 6.5.0-15-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.4.12 tk: GTK 3.24.33
    wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
```
I installed linuxbrew 1.5 years ago for a reason that i don't remember now.

```
useruser1@computerr:/$ type -a python3.10
python3.10 is /home/linuxbrew/.linuxbrew/bin/python3.10
python3.10 is /home/linuxbrew/.linuxbrew/bin/python3.10
python3.10 is /usr/bin/python3.10
python3.10 is /bin/python3.10

useruser1@computerr:/$ type -a mss
mss is /home/linuxbrew/.linuxbrew/bin/mss
mss is /home/linuxbrew/.linuxbrew/bin/mss

useruser1@computerr:/$ type -a memento-bg
memento-bg is /home/linuxbrew/.linuxbrew/bin/memento-bg
memento-bg is /home/linuxbrew/.linuxbrew/bin/memento-bg

useruser1@computerr:/$ type -a memento-timeline 
memento-timeline is /home/linuxbrew/.linuxbrew/bin/memento-timeline
memento-timeline is /home/linuxbrew/.linuxbrew/bin/memento-timeline

```
Maybe i need to somehow migrate my python3.10 to /usr/bin/python3.10 by changing $PATH and migrate all soft within .linuxbrew folder too?

It looks like a linux question, not a memento question. But maybe it's an easy one and you already know the answer.

Thank you either way.

**Comment by Aibfoba** [comment]
Fixed it by uninstalling homebrew\linuxbrew using script from homebrew's github and renaming linuxbrew directory (deleting it).

**Comment by apirrone** [comment]
Great, glad you made it work !
