### ISSUE TITLE
Hey, I met this issue on a ubuntu 22.04 virtual machine which installed on the real macOS machine

### ISSUE THREAD

**Issue by zongyangbigpolo** [apirrone/Memento#80]
![image](https://github.com/apirrone/Memento/assets/51826053/a77687b0-eb1b-48b2-b239-949c166dfcdf)

**Comment by zongyangbigpolo** [comment]
tesserocr is a big headache. I will really appreciate if you have any idea for install tesserocr==2.6.1. I have installed the latest tesserocr, but memento-bg doesn't work.

**Comment by apirrone** [comment]
Hi @l16659 ! Did you install `tesseract` like this ? 

```bash
$ sudo apt update
$ sudo add-apt-repository ppa:alex-p/tesseract-ocr-devel
$ sudo apt install tesseract-ocr
```
If yes, can you run this and show me the output ?

```bash
$ tesseract -v
```

Thanks !

**Comment by zongyangbigpolo** [comment]
Thanks very much, It works after i use the real ubuntu machine.  I use these command:
`sudo add-apt-repository universe
sudo apt update
sudo apt install python3-pip
sudo apt install git
git clone https://github.com/apirrone/Memento.git

pip install -e .
sudo apt update
sudo add-apt-repository ppa:alex-p/tesseract-ocr-devel
sudo apt install tesseract-ocr
sudo apt install tesseract-ocr-eng
sudo apt install tesseract-ocr-fra
export TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata/

 apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config`

And I have tried other gpt model with a agent(because i'm in china), it works. This is a really good project.
